# Generated by Django 2.2.6 on 2019-10-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter first name for Account', max_length=30)),
                ('last_name', models.CharField(help_text='Enter last name for Account', max_length=30)),
                ('phone_number', models.CharField(help_text='Enter phone number for Account', max_length=10)),
                ('balance', models.IntegerField(help_text='Balance for Account', verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='ATMachine',
            fields=[
                ('machine_id', models.CharField(help_text='Identification Number for ATM', max_length=16, primary_key=True, serialize=False)),
                ('current_balance', models.IntegerField(help_text='Current Balance of ATM')),
                ('minimum_balance', models.IntegerField(help_text='Minimum Balance for ATM')),
                ('last_refill', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(help_text='Card number', max_length=16, primary_key=True, serialize=False)),
                ('pin', models.CharField(help_text='Enter PIN for Card', max_length=4)),
                ('first_name', models.CharField(help_text='Enter first name for Card', max_length=30)),
                ('last_name', models.CharField(help_text='Enter last name for Card', max_length=30)),
                ('phone_number', models.CharField(help_text='Enter phone number for Account', max_length=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Activated'), ('D', 'Deactivtaed')], default='D', help_text='Card Status', max_length=1)),
                ('account', models.ForeignKey(help_text='Account that this Card is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(help_text='Identification Number for Transaction', max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved')], default='P', help_text='Transaction Status', max_length=1)),
                ('type', models.CharField(blank=True, choices=[('PHC', 'Phone Change'), ('PIC', 'PIN Change'), ('CHW', 'Cash Withdrawal'), ('CHT', 'Cash Transfer'), ('BLE', 'Balance Enquiry')], default='CHW', help_text='Tranaction Type', max_length=3)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('response_code', models.CharField(help_text='Response Code for Tranaction', max_length=1)),
                ('atm_machine', models.ForeignKey(help_text='ATM transaction was done on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ATMachine')),
                ('card', models.ForeignKey(help_text='Card used in transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Card')),
            ],
        ),
    ]
