# Generated by Django 2.2.6 on 2019-10-29 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191029_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(help_text='Enter Account Number', max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
