# Generated by Django 2.2.6 on 2019-10-30 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191029_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(help_text='Enter first name for Account', max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(help_text='Enter last name for Account', max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.CreateModel(
            name='ATMachineRefill',
            fields=[
                ('refill_id', models.CharField(help_text='Refill Identification Number for Transaction', max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)])),
                ('refill_amount', models.IntegerField(help_text='Refill amount', validators=[django.core.validators.MinValueValidator(0)])),
                ('refill_date', models.DateField(blank=True, null=True)),
                ('atm_machine', models.ForeignKey(help_text='ATM refill was done on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ATMachine')),
            ],
        ),
    ]
