# Generated by Django 2.2.6 on 2019-11-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
