# Generated by Django 2.2.6 on 2019-11-10 00:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_transaction_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, help_text='Card used in transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='response_code',
            field=models.CharField(default='0', help_text='Response Code for Tranaction', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved')], default='A', help_text='Transaction Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
