# Generated by Django 2.2.6 on 2019-11-10 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20191109_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='206186345551', help_text='Enter Account Number', max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(help_text='Initial balance for Account'),
        ),
    ]
