# Generated by Django 2.2.6 on 2019-11-10 22:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20191110_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=0, help_text='Enter Account Number', max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=0, help_text='Card number', max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 9), null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Activated'), ('D', 'Deactivtaed')], default='A', help_text='Card Status', max_length=1),
        ),
    ]
