# Generated by Django 2.2.6 on 2019-11-11 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20191110_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 10), null=True),
        ),
    ]
