# Generated by Django 2.2.6 on 2019-11-11 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20191111_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmachinerefill',
            name='refill_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
