# Generated by Django 2.2.6 on 2019-11-11 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20191111_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmachinerefill',
            name='refill_id',
            field=models.CharField(default='1014154633488358', help_text='Refill Identification Number for Transaction', max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
