# Generated by Django 2.2.6 on 2019-11-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20191111_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, help_text='Initial balance for Account'),
        ),
    ]
