# Generated by Django 2.2.6 on 2019-11-12 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20191111_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 11), null=True),
        ),
    ]
