# Generated by Django 2.2.6 on 2019-11-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20191112_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Transaction', max_length=300),
        ),
    ]
