# Generated by Django 2.2.6 on 2019-11-13 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20191112_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, help_text='Enter address of account holder', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='atmachine',
            name='address',
            field=models.CharField(blank=True, help_text='Enter address of ATM', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(blank=True, help_text='Enter address of card holder', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
