# Generated by Django 2.2.6 on 2019-11-13 05:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20191112_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account used in transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Account'),
        ),
        migrations.AlterField(
            model_name='atmachine',
            name='last_refill',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='atmachine',
            name='next_maintenance',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 12), null=True),
        ),
    ]
