# Generated by Django 2.2.6 on 2019-11-13 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20191113_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 12), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal'), ('D', 'Deposit')], default='W', help_text='Tranaction Type', max_length=3),
        ),
    ]
