# Generated by Django 2.2.6 on 2019-11-13 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20191113_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmachine',
            name='machine_id',
            field=models.CharField(help_text='Identification Number for ATM', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='ATM'),
        ),
    ]
