# Generated by Django 2.2.6 on 2019-11-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20191113_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, help_text='Account used in transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Card'),
        ),
    ]
