# Generated by Django 2.2.6 on 2019-11-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_transaction_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
    ]
