# Generated by Django 2.2.6 on 2019-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_remove_transaction_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmachine',
            name='maximum_balance',
            field=models.IntegerField(blank=True, help_text='Minimum Balance for ATM', null=True),
        ),
    ]
