# Generated by Django 2.2.6 on 2019-11-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_atmachine_maximum_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal'), ('D', 'Deposit'), ('T', 'Transfer')], default='W', help_text='Tranaction Type', max_length=3),
        ),
    ]
